version: '3.8'

services:
    oracle:
        build: .
        container_name: doctor-delta-oracle
        restart: unless-stopped
        environment:
            - NODE_ENV=production
            - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
            - PRIVATE_KEY=${PRIVATE_KEY}
            - LOCAL_RPC_URL=${LOCAL_RPC_URL}
            - USE_LOCAL_HARDHAT_NODE=${USE_LOCAL_HARDHAT_NODE}
            - ORACLE_INTERVAL_SECONDS=${ORACLE_INTERVAL_SECONDS}
            - DOCTOR_DELTA_VAULT_ADDRESS=${DOCTOR_DELTA_VAULT_ADDRESS}
