services:
    oracle:
        build: .
        image: 'docker.io/robindevferd/doctor-delta-rofl:latest'
        container_name: doctor-delta-oracle
        restart: unless-stopped
        environment:
            - NODE_ENV=production
            - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
            - PRIVATE_KEY=${PRIVATE_KEY}
            - ORACLE_INTERVAL_SECONDS=60
            - DOCTOR_DELTA_VAULT_ADDRESS=0xD30E6997119cb5330E927fe8109E7B580e977970
